# Generated by Django 4.1.7 on 2023-03-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uav',
            options={'verbose_name': 'uav', 'verbose_name_plural': 'uav'},
        ),
        migrations.AlterModelTable(
            name='uav',
            table='uav',
        ),
    ]
