# Generated by Django 4.1.7 on 2023-04-01 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizations', models.TextField()),
                ('peers', models.TextField()),
                ('uavs', models.TextField()),
                ('channels', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthenticationPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_name', models.TextField()),
                ('mspid', models.TextField()),
                ('cryptopath', models.TextField()),
                ('certpath', models.TextField()),
                ('keypath', models.TextField()),
                ('tlscertpath', models.TextField()),
                ('peerendpoint', models.TextField()),
                ('gatewaypeer', models.TextField()),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Authprofile', to='myapp.userprofile')),
            ],
        ),
    ]
