# Generated by Django 4.1.7 on 2023-04-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationpeer',
            name='cryptopath',
            field=models.TextField(blank=True, default='../management_system/'),
        ),
    ]
