# Generated by Django 4.1.7 on 2023-04-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_authenticationpeer_cryptopath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationpeer',
            name='cryptopath',
            field=models.TextField(blank=True, default='../management_system'),
        ),
    ]
