# Generated by Django 4.1.7 on 2023-04-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_authenticationpeer_cryptopath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='channels',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='peers',
            new_name='user_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uavs',
        ),
    ]
