# Generated by Django 4.1.7 on 2023-04-12 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_channels_userprofile_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionAndTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_task', models.TextField(blank=True)),
                ('mission_task_name', models.TextField(blank=True)),
                ('mission_task_coment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_task', to='myapp.userprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='mission',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
